[package]
name = "substrate-test-runner"
version = "0.1.0"
authors = ["Tomasz Drwięga <tomusdrw@gmail.com>"]
edition = "2018"

[dependencies]
# client deps
sc-executor = { git = "https://github.com/paritytech/substrate.git", rev = "462219a2b" }
sc-service = { git = "https://github.com/paritytech/substrate.git", rev = "462219a2b" }
sc-informant = { git = "https://github.com/paritytech/substrate.git", rev = "462219a2b" }
sc-network = { git = "https://github.com/paritytech/substrate.git", rev = "462219a2b" }
sc-cli = { git = "https://github.com/paritytech/substrate.git", rev = "462219a2b" }
sc-rpc-api = { git = "https://github.com/paritytech/substrate.git", rev = "462219a2b" }
sc-basic-authorship = { git = "https://github.com/paritytech/substrate.git", rev = "462219a2b" }
sc-rpc = { git = "https://github.com/paritytech/substrate.git", rev = "462219a2b" }
sc-consensus = { git = "https://github.com/paritytech/substrate.git", rev = "462219a2b" }
sc-finality-grandpa = { git = "https://github.com/paritytech/substrate.git", rev = "462219a2b" }
sc-consensus-babe = { git = "https://github.com/paritytech/substrate.git", rev = "462219a2b" }
sc-transaction-pool = { git = "https://github.com/paritytech/substrate.git", rev = "462219a2b" }
sc-client-db = { git = "https://github.com/paritytech/substrate.git", rev = "462219a2b" }
sc-client-api = { git = "https://github.com/paritytech/substrate.git", rev = "462219a2b" }
manual-seal = { package = "sc-consensus-manual-seal", git = "https://github.com/paritytech/substrate.git", rev = "462219a2b" }

# primitive deps
sp-core = { git = "https://github.com/paritytech/substrate.git", rev = "462219a2b" }
sp-blockchain = { git = "https://github.com/paritytech/substrate.git", rev = "462219a2b" }
sp-block-builder = { git = "https://github.com/paritytech/substrate.git", rev = "462219a2b" }
sp-api = { git = "https://github.com/paritytech/substrate.git", rev = "462219a2b" }
sp-application-crypto = { git = "https://github.com/paritytech/substrate.git", rev = "462219a2b" }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate.git", rev = "462219a2b" }
sp-consensus-babe = { git = "https://github.com/paritytech/substrate.git", rev = "462219a2b" }
sp-consensus = { git = "https://github.com/paritytech/substrate.git", rev = "462219a2b" }
sc-keystore = { git = "https://github.com/paritytech/substrate.git", rev = "462219a2b" }
sp-runtime = { git = "https://github.com/paritytech/substrate.git", rev = "462219a2b" }
sp-session = { git = "https://github.com/paritytech/substrate.git", rev = "462219a2b" }
sp-offchain = { git = "https://github.com/paritytech/substrate.git", rev = "462219a2b" }
sp-inherents = { git = "https://github.com/paritytech/substrate.git", rev = "462219a2b" }
sp-timestamp = { git = "https://github.com/paritytech/substrate.git", rev = "462219a2b" }
sp-keyring = { git = "https://github.com/paritytech/substrate.git", rev = "462219a2b" }
sp-externalities = { git = "https://github.com/paritytech/substrate.git", rev = "462219a2b" }
sp-storage = { git = "https://github.com/paritytech/substrate.git", rev = "462219a2b" }

# pallets
frame-system = { git = "https://github.com/paritytech/substrate.git", rev = "462219a2b" }
pallet-balances = { git = "https://github.com/paritytech/substrate.git", rev = "462219a2b" }
pallet-indices = { git = "https://github.com/paritytech/substrate.git", rev = "462219a2b" }
finality-grandpa = "0.12.3"

parity-scale-codec = "1.3.1"
structopt = "0.3.15"
env_logger = "0.7.1"
log = "0.4.8"
hyper = "0.12.35"
serde_json = "1.0"
derive_more = "0.99.9"
futures01 = { package = "futures", version = "0.1.29" }
futures = { package = "futures", version = "0.3", features = ["compat"] }
rand = "0.7"
parking_lot = "0.10"
tokio = { version = "0.2", features = ["full"] }

# Calling RPC
jsonrpc-core-client = { version = "14.2", features = ["ws"] }
jsonrpc-core = "14.2"
jsonrpc-pubsub = "14.2"
tokio-compat = { version = "0.1.6", features = ["rt-full"] }
url = "1.7"
primitive-types = "0.7"

[dev-dependencies]
node-runtime = { git = "https://github.com/paritytech/substrate.git", rev = "462219a2b" }
node-executor = { git = "https://github.com/paritytech/substrate.git", rev = "462219a2b" }
node-primitives = { git = "https://github.com/paritytech/substrate.git", rev = "462219a2b" }
node-cli = { git = "https://github.com/paritytech/substrate.git", rev = "462219a2b" }

#polkadot-runtime = { git = "https://github.com/paritytech/polkadot.git", rev = "master" }
#polkadot-core-primitives = { git = "https://github.com/paritytech/polkadot.git", rev = "master" }
#polkadot-service = { git = "https://github.com/paritytech/polkadot.git", rev = "master" }
#polkadot-cli = { git = "https://github.com/paritytech/polkadot.git", rev = "master" }
