[package]
name = "substrate-test-runner"
version = "0.1.0"
authors = ["Tomasz Drwięga <tomusdrw@gmail.com>"]
edition = "2018"

[dependencies]
node-cli = { git = "https://github.com/paritytech/substrate.git", branch = "td-test-runner", features = ["service"] }
node-runtime = { git = "https://github.com/paritytech/substrate.git", branch = "td-test-runner" }

sc-cli = { git = "https://github.com/paritytech/substrate.git", branch = "td-test-runner" }
sc-rpc-api = { git = "https://github.com/paritytech/substrate.git", branch = "td-test-runner" }
sp-runtime = { git = "https://github.com/paritytech/substrate.git", branch = "td-test-runner" }

env_logger = "0.7.1"
log = "0.4.8"
futures = "0.3"

# Calling RPC
jsonrpc-core-client = { version = "14.2", features = ["ws"] }
jsonrpc-core = "14.2"
tokio = "0.1"
url = "1.7"
